sudo: required

language: python

before_install:
  - sudo apt-get install -y python3
  - sudo apt-get install -y python3-pip
  - pip3 install PyOpenGL

branches:
  only:
    - master

script: python3 main.py