language: python

sudo: required

python:
- "3.5.2"

before_install:
  - sudo apt-get install -y python3
  - sudo apt-get install python3-tk
  - pip install PyOpenGL

branches:
  only:
    - master

script: python main.py