sudo: required

language: python

python:
  - "3.5"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U PyOpenGL
  - python3 -V
  - pip3 -V

branches:
  only:
    - master

script: python3 main.py